apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}
  version: "1.28"
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}

managedNodeGroups:
  - name: ng-dedicated-1
    instanceType: t3a.medium
    desiredCapacity: 1
    volumeSize: 20
    volumeType: gp3
    # ssh:
    #   allow: true
  - name: ng-spot-1
    instanceType: t3a.medium
    desiredCapacity: 1
    # for karpenter
    minSize: 1
    maxSize: 5
    volumeSize: 30
    volumeType: gp3
    spot: true
    labels:
      role: spot
    # below lines for K8-cluster-autoscaler only
    # propagateASGTags: true
    # iam:
    #   withAddonPolicies:
    #     autoScaler: true


iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: ${CLUSTER_NAME}-karpenter
    attachPolicyARNs:
    - arn:${AWS_PARTITION}:iam::${ACCOUNT_ID}:policy/KarpenterControllerPolicy-${CLUSTER_NAME}
    roleOnly: true

iamIdentityMappings:
- arn: "arn:${AWS_PARTITION}:iam::${ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes